# Generated by Django 5.0.7 on 2024-07-21 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='team_id',
            new_name='team',
        ),
    ]
