# Generated by Django 5.0.7 on 2024-07-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0002_rename_team_id_employee_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='region_id',
            new_name='region',
        ),
    ]
